# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class EnterpriseinfoItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    ent_uid= scrapy.Field()
    name = scrapy.Field()
    tel = scrapy.Field()
    email = scrapy.Field()
    web = scrapy.Field()
    address = scrapy.Field()
    reg_time = scrapy.Field()
    reg_ziben = scrapy.Field()
    status = scrapy.Field()
    summary = scrapy.Field()
    business_reg_code = scrapy.Field()
    org_code = scrapy.Field()
    unified_social_credit_code = scrapy.Field()
    tax_code = scrapy.Field()
    ent_type = scrapy.Field()
    industry = scrapy.Field()
    deadline = scrapy.Field()
    checkdate = scrapy.Field()
    reg_org = scrapy.Field()
    english_name = scrapy.Field()
    reg_address = scrapy.Field()
    scope_of_business = scrapy.Field()
    legal_person = scrapy.Field()
    op_type = scrapy.Field()
    base_info = scrapy.Field()
    staff_info = scrapy.Field()
    holder_info = scrapy.Field()
    invest_info = scrapy.Field()
    changeinfo = scrapy.Field()
    branch_info = scrapy.Field()
    rongzi_info = scrapy.Field()
    team_member_info = scrapy.Field()
    firm_product_info = scrapy.Field()
    touzi_info = scrapy.Field()
    jingpin_info = scrapy.Field()
    lawsuit_info = scrapy.Field()
    court_info = scrapy.Field()
    announcementcourt_info = scrapy.Field()
    punish_info = scrapy.Field()
    equity_info = scrapy.Field()
    bid_info = scrapy.Field()
    recruit_info = scrapy.Field()
    taxcredit_info = scrapy.Field()
    check_info = scrapy.Field()
    product_info = scrapy.Field()
    certificate_info = scrapy.Field()
    wechat_info = scrapy.Field()
    tm_info = scrapy.Field()
    patent_info = scrapy.Field()
    copyright_info = scrapy.Field()
    copyright_works_info = scrapy.Field()
    icp_info = scrapy.Field()
    past_ic_count_info = scrapy.Field()
    past_inverst_count_info = scrapy.Field()
    past_holder_count_info = scrapy.Field()
    past_zhixing_info = scrapy.Field()
    past_court_count_info = scrapy.Field()
    past_lawsuit_count_info = scrapy.Field()
    past_punishment_ic_info = scrapy.Field()
    past_announcement_count_info = scrapy.Field()
    past_equity_count_info = scrapy.Field()
    news_info = scrapy.Field()
    qiye_id = scrapy.Field()
    ent_faren_supplement_top = scrapy.Field()
    ent_faren_supplement_bottom = scrapy.Field()
    pass
