language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install pep8
before_script:
  - pep8 --ignore=E121,E123,E126,E226,E24,E704,E711,E712 --exclude=./alembic .
script:
  - py.test
